Fix src/esphome/components/shelly_dimmer/shelly_dimmer.h:4:33: fatal error: esphome/core/esphal.h: No such file or directory
There is no longer a esphal.h in the ESPhome core. It is now called only hal.h.